// 20241128194733
// https://monitor-ujec.imgw.pl/map/data/objects?MinLatitude=54.117258458905&MaxLatitude=54.51537850976934&MinLongitude=18.187075000000423&MaxLongitude=19.59332499999997&ZoomLevel=10&ObjectId=nul

{
  "WaterIntakes": [
    {
      "StateName": "Above02_Undefined",
      "StateDescription": "Rzędna ujęcia powyżej rzędnej wody 0,2% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Saur Neptun Gdańsk S.A.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "GOSP_KOM_mozl_4",
      "Name": " Straszyn",
      "Latitude": 54.276700,
      "Longitude": 18.547500,
      "Type": "ujęcie powierzchniowe",
      "WaterDestination": "1 - Komunalny",
      "Altitude": 40.9300,
      "WarnState": 39.8290,
      "AlarmState": 40.5630,
      "Ordinate10": 39.83000,
      "Ordinate100": 40.0700,
      "Ordinate500": 40.2200,
      "FloodingProbability": null,
      "OwnerId": 10556,
      "Province": "pomorskie",
      "Catchment": "Radunia od dopł. w Pręgowie do zapory zb. Goszyńskiego",
      "Id": 10571
    },
    {
      "StateName": "Below10_Undefined",
      "StateDescription": "Rzędna ujęcia poniżej rzędnej wody 10% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Saur Neptun Gdańsk",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_mozl_1",
      "Name": "Lipce",
      "Latitude": 54.294600,
      "Longitude": 18.651900,
      "Type": "ujęcie podziemne",
      "WaterDestination": "1 - Komunalny",
      "Altitude": 0.1500,
      "WarnState": -0.0090,
      "AlarmState": 0.0970,
      "Ordinate10": 3.26000,
      "Ordinate100": 3.6700,
      "Ordinate500": 3.8400,
      "FloodingProbability": null,
      "OwnerId": 10593,
      "Province": "pomorskie",
      "Catchment": "Polder Rokitnica (Kanał Rokitnicki)",
      "Id": 10572
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_mozl_2",
      "Name": " ",
      "Latitude": 54.309200,
      "Longitude": 18.801300,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": -0.4300,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": null,
      "Ordinate500": null,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Kaszwały",
      "Id": 10573
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_2",
      "Name": " ",
      "Latitude": 54.273000,
      "Longitude": 18.864200,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.1000,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": null,
      "Ordinate500": null,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Cedry Małe",
      "Id": 10577
    },
    {
      "StateName": "Below10_Undefined",
      "StateDescription": "Rzędna ujęcia poniżej rzędnej wody 10% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_4",
      "Name": " ",
      "Latitude": 54.256200,
      "Longitude": 18.933400,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.9800,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": 5.01000,
      "Ordinate100": 6.3500,
      "Ordinate500": 7.1000,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Kiezmark",
      "Id": 10579
    },
    {
      "StateName": "Below1_Undefined",
      "StateDescription": "Rzędna ujęcia poniżej rzędnej wody 1% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Suchy Dąb",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_6",
      "Name": " ",
      "Latitude": 54.204300,
      "Longitude": 18.726700,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.9800,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": 1.95000,
      "Ordinate100": 2.0700,
      "Ordinate500": 2.1900,
      "FloodingProbability": null,
      "OwnerId": 10605,
      "Province": "pomorskie",
      "Catchment": "Polder Suchy Dąb",
      "Id": 10581
    },
    {
      "StateName": "Above02_Undefined",
      "StateDescription": "Rzędna ujęcia powyżej rzędnej wody 0,2% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Pszczółki",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_12",
      "Name": "Różyny Kolonia",
      "Latitude": 54.214600,
      "Longitude": 18.694700,
      "Type": "ujęcie podziemne",
      "WaterDestination": "1 - Komunalny",
      "Altitude": 3.3400,
      "WarnState": 2.0900,
      "AlarmState": 2.9200,
      "Ordinate10": 1.51000,
      "Ordinate100": 1.5900,
      "Ordinate500": 1.7800,
      "FloodingProbability": null,
      "OwnerId": 10602,
      "Province": "pomorskie",
      "Catchment": "Dopływ z Różyn",
      "Id": 10587
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Saur Neptun Gdańsk",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_14",
      "Name": " Pręgowo",
      "Latitude": 54.253760,
      "Longitude": 18.472450,
      "Type": "ujęcie podziemne",
      "WaterDestination": "1 - Komunalny",
      "Altitude": 86.0000,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": 2.1300,
      "Ordinate500": 2.4900,
      "FloodingProbability": null,
      "OwnerId": 10593,
      "Province": "Pomorskie",
      "Catchment": "Martwa Wisła od Motławy do Strzyży (l)",
      "Id": 10589
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Eksploatator S.A.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_15",
      "Name": " _",
      "Latitude": 54.330500,
      "Longitude": 18.729100,
      "Type": "brzegowe",
      "WaterDestination": "",
      "Altitude": -0.1600,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": 2.1500,
      "Ordinate500": 2.4900,
      "FloodingProbability": null,
      "OwnerId": 10469,
      "Province": "pomorskie",
      "Catchment": "Polder Przejazdowo",
      "Id": 10590
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Elbląskie Przedsiębiorstwo Wodociągów i Kanalizacji Sp. Z o.o.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_17",
      "Name": " ",
      "Latitude": 54.139400,
      "Longitude": 19.398500,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": -0.1400,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": 1.0000,
      "Ordinate500": 1.0600,
      "FloodingProbability": null,
      "OwnerId": 10470,
      "Province": "Warmińsko-Mazurskie",
      "Catchment": "Polder Nowe Pole",
      "Id": 10592
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Saur Neptun Gdańsk S.A.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_27",
      "Name": " Pleniewo",
      "Latitude": 54.350300,
      "Longitude": 18.743700,
      "Type": "ujęcie podziemne",
      "WaterDestination": "1 - Komunalny",
      "Altitude": 0.8700,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": 2.1500,
      "Ordinate500": 2.4900,
      "FloodingProbability": null,
      "OwnerId": 10556,
      "Province": "pomorskie",
      "Catchment": "Czarna Łacha od polderu Przejazdowo do ujścia",
      "Id": 10602
    },
    {
      "StateName": "Above02_Undefined",
      "StateDescription": "Rzędna ujęcia powyżej rzędnej wody 0,2% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Saur Neptun Gdańsk S.A.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POW_GD_mozl_4",
      "Name": "Straszyn",
      "Latitude": 54.275300,
      "Longitude": 18.548900,
      "Type": "ujęcie powierzchniowe",
      "WaterDestination": "",
      "Altitude": 40.9000,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": 39.83000,
      "Ordinate100": 40.0700,
      "Ordinate500": 40.2200,
      "FloodingProbability": null,
      "OwnerId": 10556,
      "Province": "pomorskie",
      "Catchment": "Radunia od dopł. w Pręgowie do zapory zb. Goszyńskiego",
      "Id": 10474
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Baltic Malt Sp. z o.o.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_KZGW_mozl_6",
      "Name": " ",
      "Latitude": 54.361600,
      "Longitude": 18.668900,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.8800,
      "WarnState": -1.4080,
      "AlarmState": 0.7840,
      "Ordinate10": null,
      "Ordinate100": 2.1400,
      "Ordinate500": 2.5000,
      "FloodingProbability": null,
      "OwnerId": 10454,
      "Province": "Kujawsko-Pomorskie",
      "Catchment": "Martwa Wisła od Motławy - Opływ do Motławy (l)",
      "Id": 10653
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Browar Grupa Żywiec w Elblągu",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_KZGW_zlok_1",
      "Name": " ",
      "Latitude": 54.180100,
      "Longitude": 19.389000,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 7.9300,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": 1.4900,
      "Ordinate500": 1.5800,
      "FloodingProbability": null,
      "OwnerId": 10455,
      "Province": "warmińsko-mazurskie",
      "Catchment": "Elbląg od oddzielenia się Kan. Elbląskiego do Babicy (p)",
      "Id": 10670
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_KZGW_zlok_8",
      "Name": " ",
      "Latitude": 54.281200,
      "Longitude": 18.900400,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": -0.1100,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": null,
      "Ordinate500": null,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Błotnik",
      "Id": 10677
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Eksploatator S.A.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_KZGW_zlok_11",
      "Name": " ",
      "Latitude": 54.253800,
      "Longitude": 18.683600,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 2.3200,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": null,
      "Ordinate500": null,
      "FloodingProbability": null,
      "OwnerId": 10469,
      "Province": "Pomorskie",
      "Catchment": "Polder Lędowo",
      "Id": 10680
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": null,
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "GD_EKSP_1",
      "Name": "GD_EKSP_1",
      "Latitude": 54.370000,
      "Longitude": 18.569000,
      "Type": "",
      "WaterDestination": "",
      "Altitude": null,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": null,
      "Ordinate500": null,
      "FloodingProbability": null,
      "OwnerId": null,
      "Province": "",
      "Catchment": "",
      "Id": 10818
    },
    {
      "StateName": "Above02_Undefined",
      "StateDescription": "Rzędna ujęcia powyżej rzędnej wody 0,2% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_13",
      "Name": " ",
      "Latitude": 54.234000,
      "Longitude": 18.797100,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 2.7800,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": 1.81000,
      "Ordinate100": 1.8500,
      "Ordinate500": 1.8900,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Kanał Piaskowy do dopł. z polderu Trutnowy (l)",
      "Id": 10588
    },
    {
      "StateName": "Below10_Undefined",
      "StateDescription": "Rzędna ujęcia poniżej rzędnej wody 10% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_KZGW_zlok_9",
      "Name": " ",
      "Latitude": 54.256200,
      "Longitude": 18.933400,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.9800,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": 5.01000,
      "Ordinate100": 6.3500,
      "Ordinate500": 7.1000,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Kiezmark",
      "Id": 10678
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_11",
      "Name": " ",
      "Latitude": 54.294100,
      "Longitude": 18.807500,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.5400,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": null,
      "Ordinate500": null,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Kaszwały",
      "Id": 10586
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Saur Neptun Gdańsk S.A.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_28",
      "Name": "Krakowiec",
      "Latitude": 54.358100,
      "Longitude": 18.750500,
      "Type": "ujęcie podziemne",
      "WaterDestination": "1 - Komunalny",
      "Altitude": 4.1800,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": null,
      "Ordinate100": 2.1500,
      "Ordinate500": 2.4900,
      "FloodingProbability": null,
      "OwnerId": 10556,
      "Province": "pomorskie",
      "Catchment": "Martwa Wisła od oddzielenia się Wisły Śmiałej do Czarnej Łachy (l)",
      "Id": 10603
    },
    {
      "StateName": "Undefined_Undefined",
      "StateDescription": "Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Baltic Malt Sp. z o.o.",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_KZGW_mozl_4",
      "Name": " ",
      "Latitude": 54.361900,
      "Longitude": 18.670200,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 1.6700,
      "WarnState": -1.5550,
      "AlarmState": 0.5950,
      "Ordinate10": null,
      "Ordinate100": 2.1400,
      "Ordinate500": 2.5000,
      "FloodingProbability": null,
      "OwnerId": 10454,
      "Province": "pomorskie",
      "Catchment": "Martwa Wisła od Motławy - Opływ do Motławy (l)",
      "Id": 10651
    },
    {
      "StateName": "Below10_Undefined",
      "StateDescription": "Rzędna ujęcia poniżej rzędnej wody 10% <br/> Brak danych",
      "TrendName": "unknown",
      "OwnerName": "Urząd Gminy Cedry Wielkie",
      "State": null,
      "Trend": null,
      "CurrentForecast": null,
      "Code": "POD_GD_zlok_3",
      "Name": " ",
      "Latitude": 54.276000,
      "Longitude": 18.767400,
      "Type": "ujęcie podziemne",
      "WaterDestination": "",
      "Altitude": 0.0300,
      "WarnState": null,
      "AlarmState": null,
      "Ordinate10": 2.06000,
      "Ordinate100": 2.1500,
      "Ordinate500": 2.2400,
      "FloodingProbability": null,
      "OwnerId": 10574,
      "Province": "pomorskie",
      "Catchment": "Polder Wocławy",
      "Id": 10578
    }
  ],
  "Hydro": [
    {
      "Trend": "up",
      "Id": "154190060",
      "Name": "ELBLĄG",
      "Category": "hydro",
      "Latitude": 54.172222222222217,
      "Longitude": 19.387777777777778,
      "State": "high",
      "StatusObj": {
        "Name": "154190060",
        "Description": "ELBLĄG",
        "River": "Elbląg (54)",
        "Parameter": "B00020S",
        "CurrentState": {
          "Date": "/Date(1732819200000)/",
          "Value": 560
        },
        "PreviousState": {
          "Date": "/Date(1732818600000)/",
          "Value": 560
        },
        "LastState": null,
        "Status": 180,
        "OutdatedState": false,
        "RiverCourseKm": 9.68,
        "CatchmentArea": 1413.98,
        "Trend": 10,
        "Province": "warmińsko-mazurskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 610,
        "WarningValue": 590
      }
    },
    {
      "Trend": "down",
      "Id": "154180160",
      "Name": "GDAŃSK - SOBIESZEWO",
      "Category": "hydro",
      "Latitude": 54.346388888888889,
      "Longitude": 18.81527777777778,
      "State": "medium",
      "StatusObj": {
        "Name": "154180160",
        "Description": "GDAŃSK - SOBIESZEWO",
        "River": "Martwa Wisła (48)",
        "Parameter": "B00020S",
        "CurrentState": {
          "Date": "/Date(1732819200000)/",
          "Value": 539
        },
        "PreviousState": {
          "Date": "/Date(1732818600000)/",
          "Value": 539
        },
        "LastState": null,
        "Status": 160,
        "OutdatedState": false,
        "RiverCourseKm": 18.66,
        "CatchmentArea": 157.37,
        "Trend": -10,
        "Province": "pomorskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 570,
        "WarningValue": 550
      }
    },
    {
      "Trend": "down",
      "Id": "154180220",
      "Name": "GDAŃSKA GŁOWA ",
      "Category": "hydro",
      "Latitude": 54.266944444444441,
      "Longitude": 18.951388888888889,
      "State": "medium",
      "StatusObj": {
        "Name": "154180220",
        "Description": "GDAŃSKA GŁOWA ",
        "River": "Wisła (2)",
        "Parameter": "B00020S",
        "CurrentState": {
          "Date": "/Date(1732819200000)/",
          "Value": 546
        },
        "PreviousState": {
          "Date": "/Date(1732818600000)/",
          "Value": 547
        },
        "LastState": null,
        "Status": 160,
        "OutdatedState": false,
        "RiverCourseKm": 10.51,
        "CatchmentArea": 193807.719,
        "Trend": -10,
        "Province": "pomorskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 810,
        "WarningValue": 730
      }
    },
    {
      "Trend": "unknown",
      "Id": "154180130",
      "Name": "JUSZKOWO",
      "Category": "hydro",
      "Latitude": 54.25611111111111,
      "Longitude": 18.605,
      "State": "noData",
      "StatusObj": {
        "Name": "154180130",
        "Description": "JUSZKOWO",
        "River": "Radunia (4868)",
        "Parameter": null,
        "CurrentState": null,
        "PreviousState": null,
        "LastState": null,
        "Status": null,
        "OutdatedState": false,
        "RiverCourseKm": 13.27,
        "CatchmentArea": 790.54,
        "Trend": null,
        "Province": "pomorskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 260,
        "WarningValue": 230
      }
    },
    {
      "Trend": "up",
      "Id": "154190050",
      "Name": "NOWAKOWO",
      "Category": "hydro",
      "Latitude": 54.230555555555554,
      "Longitude": 19.363055555555558,
      "State": "high",
      "StatusObj": {
        "Name": "154190050",
        "Description": "NOWAKOWO",
        "River": "Zalew Wiślany (5119)",
        "Parameter": "B00020S",
        "CurrentState": {
          "Date": "/Date(1732818600000)/",
          "Value": 566
        },
        "PreviousState": {
          "Date": "/Date(1732818000000)/",
          "Value": 566
        },
        "LastState": null,
        "Status": 180,
        "OutdatedState": false,
        "RiverCourseKm": 2.75,
        "CatchmentArea": 1449.07,
        "Trend": 10,
        "Province": "warmińsko-mazurskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 630,
        "WarningValue": 590
      }
    },
    {
      "Trend": "up",
      "Id": "154190010",
      "Name": "NOWY DWÓR GDAŃSKI",
      "Category": "hydro",
      "Latitude": 54.214444444444446,
      "Longitude": 19.113055555555558,
      "State": "high",
      "StatusObj": {
        "Name": "154190010",
        "Description": "NOWY DWÓR GDAŃSKI",
        "River": "Tuja (5146)",
        "Parameter": "B00020S",
        "CurrentState": {
          "Date": "/Date(1732819200000)/",
          "Value": 557
        },
        "PreviousState": {
          "Date": "/Date(1732818600000)/",
          "Value": 557
        },
        "LastState": null,
        "Status": 180,
        "OutdatedState": false,
        "RiverCourseKm": 10.63,
        "CatchmentArea": 245.85,
        "Trend": 10,
        "Province": "pomorskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 590,
        "WarningValue": 570
      }
    },
    {
      "Trend": "down",
      "Id": "154180180",
      "Name": "SUCHY DĄB",
      "Category": "hydro",
      "Latitude": 54.231388888888894,
      "Longitude": 18.731944444444444,
      "State": "medium",
      "StatusObj": {
        "Name": "154180180",
        "Description": "SUCHY DĄB",
        "River": "Bielawa (4864)",
        "Parameter": "B00020S",
        "CurrentState": {
          "Date": "/Date(1732819200000)/",
          "Value": 542
        },
        "PreviousState": {
          "Date": "/Date(1732818600000)/",
          "Value": 542
        },
        "LastState": null,
        "Status": 160,
        "OutdatedState": false,
        "RiverCourseKm": 0.92,
        "CatchmentArea": 84.53,
        "Trend": -10,
        "Province": "pomorskie",
        "Note": null,
        "WaterGaugeZeroOrdinate": null,
        "WaterGaugeZeroOrdinateReferenceSystem": null,
        "AlarmValue": 620,
        "WarningValue": 600
      }
    }
  ],
  "Meteo": [
    {
      "Id": "354180140",
      "Name": "GDAŃSK-PORT PÓŁNOCNY",
      "Category": "meteo",
      "Latitude": 54.399722222222223,
      "Longitude": 18.697777777777777,
      "State": "no-precip-data",
      "StatusObj": {
        "Name": "354180140",
        "Description": "GDAŃSK-PORT PÓŁNOCNY",
        "River": "Bałtyk (0)",
        "Status": null,
        "Precip": null,
        "PrecipDaily": null,
        "Precip3HoursSum": null,
        "Precip6HoursSum": null,
        "Precip12HoursSum": null,
        "Precip24HoursSum": null,
        "MaxDailyPrecipValue": 118,
        "MaxDailyPrecipDate": "2001-07-09",
        "MaxHourPrecipValue": 4.9,
        "Province": "pomorskie",
        "Note": null
      }
    },
    {
      "Id": "254190070",
      "Name": "TOLKMICKO",
      "Category": "meteo",
      "Latitude": 54.325277777777778,
      "Longitude": 19.522499999999997,
      "State": "no-precip",
      "StatusObj": {
        "Name": "254190070",
        "Description": "TOLKMICKO",
        "River": "Zalew Wiślany (5119)",
        "Status": 0,
        "Precip": {
          "Date": "/Date(1732816800000)/",
          "Value": 0.0000,
          "DREId": 4711,
          "OperationId": "SUMGODZ_OPAD_TELEMETRIA",
          "ParameterId": "B00606B",
          "VersionId": -1,
          "Id": 28346651578501
        },
        "PrecipDaily": {
          "Date": "/Date(1732773600000)/",
          "Value": 3.7000,
          "DREId": 4711,
          "OperationId": "SUMDOB_OPAD_TELEMETRYCZNY",
          "ParameterId": "B00602E",
          "VersionId": -1,
          "Id": 28346652799301
        },
        "Precip3HoursSum": 0,
        "Precip6HoursSum": 0,
        "Precip12HoursSum": 4.2,
        "Precip24HoursSum": 7.9,
        "MaxDailyPrecipValue": 86.7,
        "MaxDailyPrecipDate": "1998-06-28",
        "MaxHourPrecipValue": 3.6,
        "Province": "warmińsko-mazurskie",
        "Note": null
      }
    },
    {
      "Id": "254180110",
      "Name": "GDAŃSK-ŚWIBNO",
      "Category": "meteo",
      "Latitude": 54.333611111111111,
      "Longitude": 18.934166666666666,
      "State": "no-precip-data",
      "StatusObj": {
        "Name": "254180110",
        "Description": "GDAŃSK-ŚWIBNO",
        "River": "Wisła (2)",
        "Status": null,
        "Precip": null,
        "PrecipDaily": null,
        "Precip3HoursSum": null,
        "Precip6HoursSum": null,
        "Precip12HoursSum": null,
        "Precip24HoursSum": null,
        "MaxDailyPrecipValue": 81.3,
        "MaxDailyPrecipDate": "1966-08-22",
        "MaxHourPrecipValue": 3.4,
        "Province": "pomorskie",
        "Note": null
      }
    },
    {
      "Id": "354190160",
      "Name": "ELBLĄG-MILEJEWO",
      "Category": "meteo",
      "Latitude": 54.223333333333336,
      "Longitude": 19.543611111111112,
      "State": "no-precip",
      "StatusObj": {
        "Name": "354190160",
        "Description": "ELBLĄG-MILEJEWO",
        "River": "Elbląg (54)",
        "Status": 0,
        "Precip": {
          "Date": "/Date(1732816800000)/",
          "Value": 0.0000,
          "DREId": 4677,
          "OperationId": "SUMGODZ_OPAD_TELEMETRIA",
          "ParameterId": "B00606B",
          "VersionId": -1,
          "Id": 28346651541301
        },
        "PrecipDaily": {
          "Date": "/Date(1732773600000)/",
          "Value": 4.9000,
          "DREId": 4677,
          "OperationId": "SUMDOB_OPAD_TELEMETRYCZNY",
          "ParameterId": "B00602E",
          "VersionId": -1,
          "Id": 28346652798101
        },
        "Precip3HoursSum": 0,
        "Precip6HoursSum": 0,
        "Precip12HoursSum": 5.2,
        "Precip24HoursSum": 10.1,
        "MaxDailyPrecipValue": 83.8,
        "MaxDailyPrecipDate": "1992-09-06",
        "MaxHourPrecipValue": 3.5,
        "Province": "warmińsko-mazurskie",
        "Note": null
      }
    },
    {
      "Id": "254190130",
      "Name": "NOWY STAW",
      "Category": "meteo",
      "Latitude": 54.134166666666665,
      "Longitude": 19.012222222222221,
      "State": "no-precip-data",
      "StatusObj": {
        "Name": "254190130",
        "Description": "NOWY STAW",
        "River": "Szkarpawa (514)",
        "Status": null,
        "Precip": null,
        "PrecipDaily": null,
        "Precip3HoursSum": null,
        "Precip6HoursSum": null,
        "Precip12HoursSum": null,
        "Precip24HoursSum": null,
        "MaxDailyPrecipValue": 80.4,
        "MaxDailyPrecipDate": "1992-09-07",
        "MaxHourPrecipValue": 3.4,
        "Province": "pomorskie",
        "Note": null
      }
    },
    {
      "Id": "254190120",
      "Name": "KMIECIN",
      "Category": "meteo",
      "Latitude": 54.187777777777775,
      "Longitude": 19.163888888888888,
      "State": "precip",
      "StatusObj": {
        "Name": "254190120",
        "Description": "KMIECIN",
        "River": "Szkarpawa (514)",
        "Status": 100,
        "Precip": {
          "Date": "/Date(1732816800000)/",
          "Value": 0.0000,
          "DREId": 100079503,
          "OperationId": "SUMGODZ_OPAD_TELEMETRIA",
          "ParameterId": "B00606B",
          "VersionId": -1,
          "Id": 28346651837201
        },
        "PrecipDaily": {
          "Date": "/Date(1732773600000)/",
          "Value": 1.5000,
          "DREId": 100079503,
          "OperationId": "SUMDOB_OPAD_TELEMETRYCZNY",
          "ParameterId": "B00602E",
          "VersionId": -1,
          "Id": 28346652807701
        },
        "Precip3HoursSum": 0,
        "Precip6HoursSum": 1.6,
        "Precip12HoursSum": 4.2,
        "Precip24HoursSum": 5.7,
        "MaxDailyPrecipValue": 78.2,
        "MaxDailyPrecipDate": "1994-10-09",
        "MaxHourPrecipValue": 3.3,
        "Province": "pomorskie",
        "Note": null
      }
    },
    {
      "Id": "254180150",
      "Name": "TRĄBKI WIELKIE",
      "Category": "meteo",
      "Latitude": 54.173333333333332,
      "Longitude": 18.536944444444448,
      "State": "no-hours-precip-data",
      "StatusObj": {
        "Name": "254180150",
        "Description": "TRĄBKI WIELKIE",
        "River": "Martwa Wisła (48)",
        "Status": 990,
        "Precip": null,
        "PrecipDaily": {
          "Date": "/Date(1732773600000)/",
          "Value": 2.6000,
          "DREId": 100044903,
          "OperationId": "254180150_B00604A",
          "ParameterId": "B00604A",
          "VersionId": -1,
          "Id": 28336160528401
        },
        "Precip3HoursSum": null,
        "Precip6HoursSum": null,
        "Precip12HoursSum": null,
        "Precip24HoursSum": null,
        "MaxDailyPrecipValue": 118.6,
        "MaxDailyPrecipDate": "2001-07-09",
        "MaxHourPrecipValue": 4.9,
        "Province": "pomorskie",
        "Note": null
      }
    }
  ]
}